import streamlit as st
import pandas as pd
import numpy as np
import requests
import plotly.graph_objects as go
import os
from datetime import datetime, timedelta
from dotenv import load_dotenv
from google import genai

# Load local environment variables (if running locally)
load_dotenv()

# Securely grab API keys from Streamlit/Environment
TIINGO_API_KEY = os.environ.get("TIINGO_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

st.set_page_config(page_title="AI Stock Predictor", page_icon="📈", layout="wide")

st.title("📈 AI Stock Predictor")

# 1. Validation Check: Ensure keys exist before trying to run
if not TIINGO_API_KEY or not GEMINI_API_KEY:
    st.error("⚠️ **API Keys Missing!**")
    st.write("Please ensure `TIINGO_API_KEY` and `GEMINI_API_KEY` are securely added to your Streamlit Cloud Secrets.")
    st.stop()

# 2. Sidebar Configuration
st.sidebar.header("Market Parameters")
ticker = st.sidebar.text_input("Stock Ticker", value="AAPL").upper()
days_back = st.sidebar.slider("Historical Data (Days)", min_value=30, max_value=365, value=180)

# 3. Tiingo API Data Fetcher
@st.cache_data(ttl=3600) # Caches data for 1 hour to prevent API limits
def fetch_tiingo_data(symbol, days):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {TIINGO_API_KEY}'
    }
    start_date = (datetime.today() - timedelta(days=days)).strftime('%Y-%m-%d')
    url = f"https://api.tiingo.com/tiingo/daily/{symbol}/prices?startDate={start_date}"
    
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        data = response.json()
        if not data:
            return pd.DataFrame()
        df = pd.DataFrame(data)
        df['date'] = pd.to_datetime(df['date']).dt.tz_localize(None)
        df.set_index('date', inplace=True)
        return df
    return None

# 4. Process Data & Calculate Beta
with st.spinner(f"Querying Tiingo for {ticker} matrices..."):
    df = fetch_tiingo_data(ticker, days_back)
    spy_df = fetch_tiingo_data("SPY", days_back) # S&P 500 for baseline

if df is None or df.empty:
    st.error(f"Could not fetch data for '{ticker}'. Please verify the ticker symbol.")
else:
    # Math: Calculate Beta vs Market
    df['Return'] = df['close'].pct_change()
    if spy_df is not None and not spy_df.empty:
        spy_df['Return'] = spy_df['close'].pct_change()
        aligned = pd.concat([df['Return'], spy_df['Return']], axis=1).dropna()
        aligned.columns = ['Stock', 'SPY']
        
        # Beta = Covariance(Stock, Market) / Variance(Market)
        covar = aligned.cov().iloc[0, 1]
        var_spy = aligned['SPY'].var()
        beta = covar / var_spy if var_spy != 0 else np.nan
    else:
        beta = np.nan

    # 5. Dashboard Metrics
    current_price = df['close'].iloc[-1]
    prev_price = df['close'].iloc[-2]
    price_change = current_price - prev_price
    pct_change = (price_change / prev_price) * 100

    st.markdown("---")
    col1, col2, col3 = st.columns(3)
    col1.metric("Current Close", f"${current_price:.2f}", f"{price_change:.2f} ({pct_change:.2f}%)")
    col2.metric("Calculated Beta", f"{beta:.2f}" if not np.isnan(beta) else "N/A", "vs S&P 500 (SPY)")
    col3.metric("Recent Trading Volume", f"{df['volume'].iloc[-1]:,.0f}")

    # 6. Plotly Interactive Chart
    st.subheader(f"Historical Candlestick Chart: {ticker}")
    fig = go.Figure(data=[go.Candlestick(x=df.index,
                    open=df['open'], high=df['high'],
                    low=df['low'], close=df['close'],
                    increasing_line_color='#00ffcc', decreasing_line_color='#ff007f')])
    
    fig.update_layout(xaxis_rangeslider_visible=False, height=500, template="plotly_dark", margin=dict(l=0, r=0, t=30, b=0))
    st.plotly_chart(fig, use_container_width=True)

    # 7. Gemini Neural Prediction
    st.markdown("---")
    st.subheader("🧠 AI Analytics Engine")
    
    if st.button("Generate Neural Prediction"):
        with st.spinner("Initializing Google Gemini..."):
            try:
                # Format context for the LLM
                recent_data = df.tail(10)[['close', 'volume']].to_string()
                prompt = f"""
                You are a highly skilled quantitative financial analyst. 
                Analyze the following recent closing prices and volume data for {ticker}.
                The stock has a calculated Beta of {beta:.2f} against the S&P 500.
                
                Recent 10-Day Data Matrix:
                {recent_data}
                
                Provide a professional, concise assessment of the current momentum, potential volatility indicators based on the beta and volume, and a short-term qualitative prediction.
                Conclude with a strict disclaimer that this output is generated by an AI and does not constitute financial advice.
                """
                
                # Execute Gemini Call
                client = genai.Client(api_key=GEMINI_API_KEY)
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt
                )
                
                st.success("Analysis Complete")
                st.write(response.text)
                
            except Exception as e:
                st.error(f"Neural Engine Error: {e}")
